### ISSUE TITLE
Manual tweaks to improve the Rephetio feature heatmap and machine learning figure

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-manuscript#11]
Currently the [manuscript has](https://greenelab.github.io/connectivity-search-manuscript/v/6ac122b30b9b92ae99ebf6dc61768fdd6647d573/#fig:rephetio) the following figure and caption for the project rephetio ML approach:

> ![image](https://user-images.githubusercontent.com/1117703/85303548-a07f6480-b478-11ea-8589-79af36da7d97.png)

I think we can make this fit the connectivity search aesthetic a bit better. I've made some improvements at https://slides.com/dhimmel/rocky2019#/11/1/3:

> ![image](https://user-images.githubusercontent.com/1117703/85303773-f05e2b80-b478-11ea-9de3-23b0924ee21b.png)

The additions are as follows:

- axis labels
- dashed divider for treatments/non-treatments, and better labeling of treatments
- changing the metapath to use the connectivity search encircled abbreviation format

other ideas:

- compound-disease pairs can use connectivity search background highlights 
Like ![image](https://user-images.githubusercontent.com/1117703/85304413-b8a3b380-b479-11ea-9f24-92ff8f91df5c.png) but the edge has no label because these are just endpoints.
- remove status column if treatment/non-treatment is clear from other visual element

The SVG source is [available here](https://raw.githubusercontent.com/dhimmel/learn/7668c97b2a6f348479b70fa40c3d7db424584315/prediction/figure/example-feature-matrix.svg?sanitize=true). @vincerubinetti how doable do you think these changes are?

Also thinking of making this a 1x2 figure where A is the new metagraph with new node colors created for connectivity search (after https://github.com/hetio/het.io/issues/36 is fixed). B would be the rephetio feature heatmap above.

**Comment by vincerubinetti** [comment]
I think the changes in your slides look good. Best way to match the aesthetic is to use the same font, Lato, which it looks like you have, and to use the same colors where possible.

> compound-disease pairs can use connectivity search background highlights. Like image but the edge has no label because these are just endpoints.

I think that's a nice idea. You could also put a nice `. . .` in between.

> remove status column if treatment/non-treatment is clear from other visual element

I think the "treatments" box you've added is a much clearer and nicer way to indicate the status than the status column, and i think you could remove it.

---

If you've already implemented some changes in your slides.com presentation, do you just want to continue the changes there? Can it export as svg? I know a lot of people in the lab have made figures via powerpoint. Otherwise, can you zoom in and scale up the slide.com figure enough to make a really high resolution raster image?

I could also edit the original matplotlib in inkscape to re-add your changes. Or make it look super pretty and do it by hand. But those would take time.

**Comment by dhimmel** [comment]
I could probably make the figure by continuing with slides.com. would copy
the slide and remake with a white background for the manuscript.

I probably wouldn't be able to do background color for compound–disease
labels.
Matplotlib will struggle doing anything fancy with the labels. So to change
them I'd just cover them in slides.

How much time would it take for you to do it via the SVG / illustrator? If
you think it'd be most efficient for me to do the additional tweaks in
slides, I can do that

**Comment by vincerubinetti** [comment]
Overall it'd be faster for you to do it, but i could do it a bit more cleanly with inkscape or manually. Also I have more free time right now that you do. So I'll do it.

**Comment by vincerubinetti** [comment]
[example-feature-matrix.zip](https://github.com/greenelab/connectivity-search-manuscript/files/4827042/example-feature-matrix.zip)

@dhimmel Ready for proof read

**Comment by dhimmel** [comment]
> Ready for proof read

A true masterpiece!

It displays properly for me in Chrome, but not Inkscape or my desktop viewer (the x-axis metapath labels don't render properly). So we should also export a high-rez PNG (like 300 dpi?) as a backup.

Also would it be possible to create a version where the new metagraph is on the left and this figure is on the right, with AB labels?

**Comment by vincerubinetti** [comment]
Transparent raster version:

![example-feature-matrix](https://user-images.githubusercontent.com/8326331/85607246-e9bee800-b621-11ea-8715-28c4a7ea9599.png)

The SVG version uses advanced svg features that wont render properly in inkscape, online converters, word documents, etc. So only use the SVG version if you're sure it's going to be viewed in a modern browser like Firefox or Chrome.

**Comment by dhimmel** [comment]
Ah found a typo in the final metapath

**Comment by vincerubinetti** [comment]
For future reference, I'm using https://vincerubinetti.github.io/svg-to-png/ to save it as a high resolution png.

**Comment by vincerubinetti** [comment]
Updated to fix typo:
[figure.zip](https://github.com/greenelab/connectivity-search-manuscript/files/4827136/figure.zip)

**Comment by vincerubinetti** [comment]
Updated to fix typo, and to include version for black backgrounds.

[example-feature-matrix.zip](https://github.com/greenelab/connectivity-search-manuscript/files/4827164/example-feature-matrix.zip)

**Comment by dhimmel** [comment]
> Updated to fix typo, and to include version for black backgrounds.

Awesome. The dark background version will be great for presentations!

Linking to the [notebook on Google Collab](https://colab.research.google.com/drive/1YPThLefaSb9xKh2q4TEVjoU9ln-41tYC?usp=sharing) we used to change the diverging colormap colors for the heatmap. It was based on the rephetio notebook [`8-feature-example-viz.ipynb`](https://nbviewer.jupyter.org/github/dhimmel/learn/blob/7668c97b2a6f348479b70fa40c3d7db424584315/prediction/8-feature-example-viz.ipynb).

**Comment by vincerubinetti** [comment]
> Also would it be possible to create a version where the new metagraph is on the left and this figure is on the right, with AB labels?

How's this:

![figure](https://user-images.githubusercontent.com/8326331/85732389-52ad6b00-b6c9-11ea-8a76-89d14890da69.png)

[figure.zip](https://github.com/greenelab/connectivity-search-manuscript/files/4831720/figure.zip)

**Comment by dhimmel** [comment]
> How's this:

Nice. You can see it in the [manuscript here](https://greenelab.github.io/connectivity-search-manuscript/v/2615563a45319a00f213b1e148caad241b5064eb/#fig:rephetio).

FYI i mentioned earlier that we want minimal margins. I think I should amend my comment that we still want some margin, like 2-5 pixels. Although as I look at journal guidelines, I'm not actually sure. Some seem to want zero margins. @cgreene in your experience, do we want a small margin or no margin at all?

For the manubot view, 2-5 pixel margins would be nice for fullscreen view:

> ![image](https://user-images.githubusercontent.com/1117703/85742118-fa7a6700-b6d0-11ea-8887-b62bf94d673b.png)

But otherwise are not needed.

**Comment by cgreene** [comment]
I have no idea!

**Comment by vincerubinetti** [comment]
@dhimmel For your screenshot, perhaps it's a better idea to add margins to the lightbox plugin itself.

**Comment by dhimmel** [comment]
> For your screenshot, perhaps it's a better idea to add margins to the lightbox plugin itself.

Would it be possible to to detect the margin from a property like:

```markdown
![](){#fig:id width="100%" lightbox-margin="5px" .white}
```

What syntax would you recommend?

**Comment by vincerubinetti** [comment]
Let's get a new issue for that. I'm not sure having an extra property is the right way to do it.
