### ISSUE TITLE
Write the Webapp & Frontend methods section

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-manuscript#29]
Currently, the "Webapp & Frontend" [section is just a placeholder](https://github.com/greenelab/connectivity-search-manuscript/blob/f4925018d18367b07db72e9b64043c08ee06e9a0/content/05.main-text.md?plain=1#L758-L760). I was thinking this section could describe some the technical aspects of

- https://het.io/search/
- https://github.com/greenelab/connectivity-search-frontend

I envision a couple of paragraphs that describe which frameworks we use and any major contributions or novel aspects of the frontend. The [Backend Database & API](https://greenelab.github.io/connectivity-search-manuscript/#backend-database-api) methods section might be a helpful example here.

@vincerubinetti would you be able to draft a couple paragraphs here or provide a list of  things we should mention?

**Comment by vincerubinetti** [comment]
I can write up a few paragraphs. I'll add it to my to do list.
