### ISSUE TITLE
Post-acceptance editorial requests from Gigascience

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-manuscript#49]
From an 2023-05-17 email to Casey Greene from the GigaScience Editorial Office:

***

Dear Casey,

Your manuscript "Hetnet connectivity search provides rapid insights into how two biomedical entities are related" (GIGA-D-23-00005R1)  is acceptable for publication in GigaScience.

Before we proceed to the production stage, please address the following editorial points:

1) GigaDB citation
 Please include a citation to your new GigaDB dataset (including the DOI link) to your reference list, and cite this by number from the data availability section.

    The citation is:
[xx] Himmelstein DS, Zietz M, Rubinetti V, Kloster K, Heil BJ, Alquaddoomi F et al.  Supporting data for "Hetnet connectivity search provides rapid insights into how two biomedical entities are related" GigaScience Database. 2023. http://dx.doi.org/10.5524/102389

    In the data "availability" section, please write something along the lines, "An archival copy of the code and supporting data is available via the GigaScience repository, GigaDB [xx]".

2) For a [technical note](https://academic.oup.com/gigascience/pages/technical_note), the "availability" section should have the title: "Availability of supporting source code and requirements".

    In this section, list the following:

    Project name: e.g. My bioinformatics project (URL + citation [xx])
Project home page: e.g. https://github.com/ISA-tools
Operating system(s): e.g. Platform independent
Programming language: e.g. Java
Other requirements: e.g. Java 1.3.1 or higher, Tomcat 4.0 or higher
License: e.g. GNU GPL, FreeBSD etc.
RRID: if applicable, e.g. RRID: SCR_014986
biotools ID: XYZ

    (you can repeat this format if you have several sub-projects)

3) We treat URLs and other internet sources (doi, ftp)  as citable items. For each URL/doi (software repo, database, hompage etc) that's mentioned in the text, please create a numbered reference in the bibliography and cite the URL by reference number in the text, rather than using a hyperlink directly. Please refer to our citation guidelines for details.

4) Please structure your abstract (Background, Findings, Conclusions).

5) Please upload the text file in an editable format to Editorial Manager (Word or LaTex).

6)  Please also ensure that your revised manuscript conforms to the journal style, which can be found in the [Instructions for Authors](https://academic.oup.com/gigascience/pages/instructions_to_authors) on the journal homepage

Once you have made the necessary corrections, please submit a revised manuscript online at https://www.editorialmanager.com/giga/

If you have forgotten your username or password please use the "Send Login Details" link to get your login information. For security reasons, your password will be reset.

Thank you for publishing with GigaScience. We look forward to receiving your revised manuscript soon.

Best wishes,
Hans Zauner
GigaScience

**Comment by dhimmel** [comment]
[Search](https://academic.oup.com/gigascience/search-results?f_TocHeadingTitle=TECHNICAL+NOTE) to see recently published technical notes. Recent examples:

- https://doi.org/10.1093/gigascience/giad030

**Comment by dhimmel** [comment]
Following are done (mostly in https://github.com/greenelab/connectivity-search-manuscript/pull/50):

- GigaDB citation
- Availability of supporting source code and requirements
- structure your abstract
- journal style (except for citation style), can apply the [CSL](https://github.com/citation-style-language/styles/blob/256250be9c6ab34bba4a070b5c050f7848b37beb/gigascience.csl), but its not great (but not sure if that's because of the journal's style or issues with the CSL)

> For each URL/doi (software repo, database, hompage etc) that's mentioned in the text, please create a numbered reference in the bibliography and cite the URL by reference number in the text, rather than using a hyperlink directly. 

Let's respond to this request with something like: "We've gone through all hyperlinks and inline URLs in the manuscript. The ones that remain without a dedicated numbered reference are not be appropriate for the bibliography in our opinion. We would prefer that the production process strips the hyperlinks than for us to convert the links to dedicated references. Ideally, the article production can preserve the hyperlinks as is."

> Please upload the text file in an editable format to Editorial Manager (Word or LaTex).

@cgreene any preference on Word of LaTeX? Word might be easier? I imagine both will need some small hand tweaks. All of our images are raster PNGs.

**Comment by cgreene** [comment]
I agree word might be easier - shall we go with that? We've used manubot -> docx in other contexts that way.

**Comment by dhimmel** [comment]
Running an [adhoc build](https://github.com/greenelab/connectivity-search-manuscript/actions/runs/5062895501) with docx and latex outputs at  [`manuscript-5062895501-b6532fa.zip`](https://github.com/greenelab/connectivity-search-manuscript/files/11549019/manuscript-5062895501-b6532fa.zip). Will follow up with hand-edited DOCX

**Comment by dhimmel** [comment]
Okay I edited the docx to produce [`2023-05-23_gigascience-connectivity-search-submission.docx`](https://github.com/greenelab/connectivity-search-manuscript/files/11549188/2023-05-23_gigascience-connectivity-search-submission.docx). My edits included

- added keywords
- frontmatter: remove author funding, add emails
- copy in gigascience style references, in addition to the manubot style references

So @cgreene you should be good to go ahead with the submission. Ideally you can not the following:

- that hyperlinks can be dropped if necessary, we have decided not to create any more references for them (draft above)
- that the DOCX has the references in two styles, first the gigascience style according to [their CSL](https://github.com/citation-style-language/styles/blob/256250be9c6ab34bba4a070b5c050f7848b37beb/gigascience.csl) and then the Manubot style which in some cases appears to provide more pertinent information.
- they can reference the [HTML](https://greenelab.github.io/connectivity-search-manuscript/v/b6532fafbc126c0818c612febf86968e6fa8e21b/) or [PDF](https://greenelab.github.io/connectivity-search-manuscript/v/b6532fafbc126c0818c612febf86968e6fa8e21b/manuscript.pdf) manuscript if there are questions about the DOCX formatting.

I think that's all

**Comment by dhimmel** [comment]
Okay I edited the docx to produce [`2023-05-23_gigascience-connectivity-search-submission.docx`](https://github.com/greenelab/connectivity-search-manuscript/files/11549188/2023-05-23_gigascience-connectivity-search-submission.docx). My edits included

- added keywords
- frontmatter: remove author funding, add emails
- copy in gigascience style references, in addition to the manubot style references

So @cgreene you should be good to go ahead with the submission. Ideally you can not the following:

- that hyperlinks can be dropped if necessary, we have decided not to create any more references for them (draft above)
- that the DOCX has the references in two styles, first the gigascience style according to [their CSL](https://github.com/citation-style-language/styles/blob/256250be9c6ab34bba4a070b5c050f7848b37beb/gigascience.csl) and then the Manubot style which in some cases appears to provide more pertinent information.
- they can reference the [HTML](https://greenelab.github.io/connectivity-search-manuscript/v/b6532fafbc126c0818c612febf86968e6fa8e21b/) or [PDF](https://greenelab.github.io/connectivity-search-manuscript/v/b6532fafbc126c0818c612febf86968e6fa8e21b/manuscript.pdf) manuscript if there are questions about the DOCX formatting.

Images will likely have to be submitted separately. I think all of our images are currently PNG, so maybe just save as from the HTML manuscript according to whatever naming they want.

I think that's all

**Comment by cgreene** [comment]
Submitted! 🙌

**Comment by dhimmel** [comment]
A couple more editorial requests sent from 2023-05-29:

***

Dear Casey,

Thank you for submitting your revised manuscript. Indeed we'd need to drop the in-text URLs for the GigaScience/OUP format. Looking over the current text with URLs, it seems some of the text would no longer make sense without the link (for example "see [source with link]"). Could you please go over the text again and remove the URLs, and, where necessary, either replace them with a citation, or change the text accordingly?

In reference 63 (the GigaDB reference), please also add the doi link for your dataset (http://dx.doi.org/10.5524/102389).

Did you also register connectivity-search for an RRID? Please include this in addition to the biotools ID in the avaial. section.

Once you have made the necessary corrections, please submit a revised manuscript online at <https://www.editorialmanager.com/giga/>.

We look forward to publishing your manuscript.

Kind regards,
Hans Zauner

**Comment by dhimmel** [comment]
Created an ad-hoc [run](https://github.com/greenelab/connectivity-search-manuscript/actions/runs/5145436918) to build the DOCX with artifacts in [`manuscript-5145436918-79b83d7.zip`](https://github.com/greenelab/connectivity-search-manuscript/files/11626351/manuscript-5145436918-79b83d7.zip). I created a lua filter to remove the hyperlinks just for the DOCX output in https://github.com/greenelab/connectivity-search-manuscript/commit/af8cfeac77e5717dbffa6e42f657b20e8650fc15.

@cgreene here is the revised submittable: [`2023-06-01_gigascience-connectivity-search-submission.docx`](https://github.com/greenelab/connectivity-search-manuscript/files/11626429/2023-06-01_gigascience-connectivity-search-submission.docx) which includes the following manual edits:

- Copied author information and keywords `2023-05-23_gigascience-connectivity-search-submission.docx`
- Copied references from a local build using the modified GigaScience CSL from 79b83d77cd74c8914bba55bf1beeb99ace4c9d2a

Here's an update you can provide to Hans Zauner.

We've removed all main text hyperlinks. The remaining main text links are internal to the manuscript (i.e. to figures, sections, tables, references).

We have added the DOI to the GigaDB reference by tweaking the [CSL style](https://github.com/greenelab/connectivity-search-manuscript/commit/79b83d77cd74c8914bba55bf1beeb99ace4c9d2a) for Gigascience. We provide the references in two formats: first the Gigascience format as per the CSL and second the Manubot style. If the references need any more reformatting, it is our preference that this be handled by the production team.

We have registered RRID:SCR_023630 and included it in the manuscript.

**Comment by dhimmel** [comment]
# Email to Casey on 2023-06-06

Dear Prof. Greene,

I am pleased to inform you that your manuscript "Hetnet connectivity search provides rapid insights into how two biomedical entities are related" (GIGA-D-23-00005R3) has been accepted for publication in GigaScience.

Before publication, our production team will check the format of your manuscript to ensure that it conforms to the standards of the journal. They will be in touch shortly to request any necessary changes, or to confirm that none are needed. This is the last chance to update any preprint versions of this paper as they will be frozen upon publication.

Any final comments from our reviewers or editors can be found, below. Please quote your manuscript number, GIGA-D-23-00005R3, when inquiring about this submission.

We look forward to publishing your manuscript and I do hope you will consider GigaScience again in the future.

Best wishes,
Nicole Nogoy, Ph.D
GigaScience

Comments:

Please also take a moment to check our website at REDACTED for any additional comments that were saved as attachments. Please note that as GigaScience has a policy of open peer review, you will be able to see the names of the reviewers.

Copying the website review history page screenshot here:

![image](https://github.com/greenelab/connectivity-search-manuscript/assets/1117703/2be79822-6763-4ddb-a7c3-167324d309ce)
