### ISSUE TITLE
Gigascience proof review

### ISSUE THREAD

**Issue by dhimmel** [greenelab/connectivity-search-manuscript#52]
We received the proof to review via the PXE5 system. Here is the PDF proof export: [`giad047.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/11833822/giad047.pdf). Also we can see the changes applied by the copyeditor at [giad047-copy-editor-changes.pdf](https://github.com/greenelab/connectivity-search-manuscript/files/11842114/giad047-copy-editor-changes.pdf).

The header of the PXE5 system includes:

> In case of any difficulty, please contact via US Toll Free: 1.800.767.1518 x 2035 or email: aptarahelpdesk@aptaracorp.com.

At a first glance, this will need a lot a work, specifically the references where most links to articles have been removed. Also checking carefully what the proof team has changed, I don't see any tracked changes or edit history from the final submission, but haven't looked hard.

Message to Casey (link to open proof removed):

> Automated Mailer GIGASCI <gigascience@aptaracorp.com>
> Date: Wednesday, June 21, 2023 at 9:26 PM
> To: Greene, Casey
> Cc: oup-prod@aptaracorp.com
> Subject: Giga Science: giad047 - Manuscript No. [GIGA-D-23-00005] - check your proof
> 
> [External Email - Use Caution]
> 
> Dear Casey S. Greene,
> 
> Your manuscript proof is ready for you to check.
> 
> What you need to do now:
> 
> Please check and approve your proof within two working days.
> Respond to all copyeditor queries. Refer to the tutorial videos, FAQs, and help button for guidance on how to make changes and write comments.
> If necessary, use the Query Manager in the Editing tool to write instructions for the typesetter to carry out additional corrections.
> 
> Click here to Open the Proof
> 
> Notes:
> 
> The option for pop-up windows should be enabled in your Internet browser to view the author instructions page.
> Should the article link fail please clear your browser cache and retry.
> If you need further assistance, please let us know by replying to this email.
> 
> What happens next:
> 
> We will prepare your manuscript for online publication.
> You will receive an email on publication about paying publication charges if applicable. There is a charge of £50 per page for each page in an article after the first 20 pages.
> Best wishes,
> 
> Giga Science production team
> Oxford University Press

Here is the documentation popup about PXE5:

<details>
<summary>Expand for PXE5 welcome message</summary>

### Welcome to Oxford University Press' online proof-correction system

This system provides an online editing environment for reviewing your proof and providing proof corrections. When you apply corrections in the "Edit" mode, you are updating the article's production master file in real time significantly reducing the potential for ambiguity and misinterpretation. This helps us to publish your article sooner.

On this system, you will be able to...

- Make textual proof corrections
- Respond to queries
- Add comments, queries or instructions
- View your corrected proof as a PDF
- Upload files
- Sign off article to OUP staff for next phase of the production process

When using the system, please complete the following steps:

1. Carefully review the whole article.
2. Make amendments directly in the text as much as possible in the Edit mode (or via the Add Comments tool ).
3. Respond to author queries (all queries must be answered before you submit your corrections).
4. As far as possible, limit your edits to the correction of errors and responses to author queries.
5. Please submit corrections (along with any files) when you have answered all of the author queries, proofread the entire article and reviewed your changes. Selecting 'Finish and Submit' moves the article to the next stage of the workflow and you will not be able to access the article via the system. Select 'Close' if you wish to save your changes and return to the article later.

### Notes

PXE5 is an online XML Editing Application and will be affected by your Internet speed and connectivity.
Low-resolution figures are used to ensure fast rendering & as a preview. To see the actual output files, please refer to the Proof PDF under the PDF tab.

### Help

Do refer to our [PXE User Guide](https://powerxeditor.aptaracorp.com/pxeoup/UserDocument/UserGuide/Generic_PXE5_UserGuide_Editor.pdf), both before or while using the system

OUP production staff are on hand if you need any assistance using the platform; Alternatively, you can use the Live Chat feature to submit queries direct to the support team at the software provider.

If you have problems logging in or using the tool, please contact US Toll Free: 1.800.767.1518 x 2035 or email: [aptarahelpdesk@aptaracorp.com](mailto:aptarahelpdesk@aptaracorp.com)

</details>

Archiving a copy of [`Generic_PXE5_UserGuide_Editor.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/11834815/Generic_PXE5_UserGuide_Editor.pdf)

**Comment by dhimmel** [comment]
# Reference Woes

See https://github.com/greenelab/connectivity-search-manuscript/issues/49 for prior reference formatting requests.

Here's what the references look like in PXE5:

![image](https://github.com/greenelab/connectivity-search-manuscript/assets/1117703/981b5675-ef97-477f-84cf-796294c63766)

And here are the extracted reference requests

- Please provide the city of publication for Refs. 1, 3, 4, 31, 32, 34, 43, 44, 45, 49, 51
- Please provide the volume number and page range for Refs. 2 and 15
- Please provide the editor(s) if applicable and the city of publication for the following references: 12, 13, 19, 25, 26, 27, 28, 38, and 48.
- Please provide the page range for the following references: 14, 18, 22, 35, 36, 39, 41, and 53
- Please provide editor(s) if applicable. 17
- Please provide editor(s) and year of publication 24
- Please provide editor(s) if applicable, publisher, and city of publication 29
- Please provide the URL for the following references: 46, 50, and 52.
- Please list authors 47

**Comment by dhimmel** [comment]
# Duplicated affiliations

When an affiliation is shared across authors, it is repeated as multiple entries in the affiliation list:

![image](https://github.com/greenelab/connectivity-search-manuscript/assets/1117703/043553ff-cbab-4c7a-8110-04cc2974b220)

I called the Aptera support number above and spoke with Simran. She said to email the request to `aptarahelpdesk@aptaracorp.com` and they can work on deduplicating the affiliations.

In https://github.com/greenelab/connectivity-search-manuscript/commit/46e165b38bf3bf03e17dbdcaa19eae7c396bc284, I updated the source affiliations for the Gigascience style with zip codes and to let manubot deduplicate. Here's what the affiliations should be:

1. Department of Systems Pharmacology and Translational Therapeutics, University of Pennsylvania, Philadelphia, PA 19104, USA
2. Related Sciences, Denver, CO 80202, USA
3. Department of Biomedical Informatics, Columbia University, New York, NY 10032, USA
4. Center for Health AI, University of Colorado School of Medicine, Aurora, CO 80045, USA
5. Carbon, Inc., Redwood City, CA 94063, USA
6. Department of Computer Science, North Carolina State University, Raleigh, NC 27606, USA
7. Genomics and Computational Biology Graduate Group, Perelman School of Medicine, University of Pennsylvania, Philadelphia, PA 19104, USA
8. Department of Biochemistry and Molecular Genetics, University of Colorado School of Medicine, Aurora, CO 80045, USA
9. Department of Pathology, Perelman School of Medicine University of Pennsylvania, Philadelphia, PA 19104, USA
10. School of Computing, University of Utah, Salt Lake City, UT 84112, USA
11. Integrative Biology, Internal Medicine Research Unit, Worldwide Research, Development, and Medicine, Pfizer Inc., Cambridge, MA 02139, USA
12. Neurogenomics, Translational Sciences, Neurology Business Group, Eisai Inc., Cambridge, MA 02140, USA


## Email

Greetings Aptera Help Desk,

I'm an author on article giad047 currently in the proofing stage at Gigascience. I noticed that the affiliations are not deduplicated (such that the same affiliation has multiple numbers).

I called and spoke with Simran. She mentioned that we should email a request to update the affiliations.

Please let us know if you have any questions and notify us when complete (don't want to create any conflicts by simultaneously editing).

Best,
Daniel


## Email Response

Dear Daniel,

Thanks for your email. The affiliations you can delete from the PXE interface by yourself.

Place your cursor at the desired affiliation. The screenshot below:
 
![image](https://github.com/greenelab/connectivity-search-manuscript/assets/1117703/b1e5891c-25dc-4206-b1d0-bf3b99df4688)

After placing the cursor select the below mentioned button:

![image](https://github.com/greenelab/connectivity-search-manuscript/assets/1117703/54725ea2-ee1f-4d9a-9860-15d7cd8365e7)

Then click on the below mentioned options whether you want to delete Organization or the whole affiliation :
 
![image](https://github.com/greenelab/connectivity-search-manuscript/assets/1117703/e5fb44e3-453c-4123-beaa-f467b52a8e55)

After this all the affiliations automatically change with the new sequence.

Hope this will resolve your question. Feel free to write to us in case of any queries.

Regards,
Manish Chauhan
Technical Support | PXE
Aptara, Inc. | Transforming Content into Knowledge
[aptarahelpdesk@aptaracorp.com](mailto:aptarahelpdesk@aptaracorp.com) | [www.aptaracorp.com](http://www.aptaracorp.com/)
o: +1.800.767.1518 x2035 | o: +91.120.7182424/7192525 x 2035

## Reply

Thank you Manish for the quick reply. I tried editing the affiliations as you suggested but it is difficult for me since I am not familiar with the PXE5 editor and the edits also require adding affiliations.

It would be most efficient if your team is able to make these changes. To assist, I'm including the author with their correct affiliation numbers and the corresponding affiliation texts. I've also added the postcodes as requested. Can your team process these edits?

Daniel S. Himmelstein 1,2
Michael Zietz 1,3
Vincent Rubinetti 1,4
Kyle Kloster 5,6
Benjamin J. Heil 7
Faisal Alquaddoomi 4,8
Dongbo Hu 9
David N. Nicholson 1
Yun Hao 7
Blair D. Sullivan 10
Michael W. Nagle 11,12
Casey S. Greene 1,4,8

1. Department of Systems Pharmacology and Translational Therapeutics, University of Pennsylvania, Philadelphia, PA 19104, USA
2. Related Sciences, Denver, CO 80202, USA
3. Department of Biomedical Informatics, Columbia University, New York, NY 10032, USA
4. Center for Health AI, University of Colorado School of Medicine, Aurora, CO 80045, USA
5. Carbon, Inc., Redwood City, CA 94063, USA
6. Department of Computer Science, North Carolina State University, Raleigh, NC 27606, USA
7. Genomics and Computational Biology Graduate Group, Perelman School of Medicine, University of Pennsylvania, Philadelphia, PA 19104, USA
8. Department of Biochemistry and Molecular Genetics, University of Colorado School of Medicine, Aurora, CO 80045, USA
9. Department of Pathology, Perelman School of Medicine University of Pennsylvania, Philadelphia, PA 19104, USA
10. School of Computing, University of Utah, Salt Lake City, UT 84112, USA
11. Integrative Biology, Internal Medicine Research Unit, Worldwide Research, Development, and Medicine, Pfizer Inc., Cambridge, MA 02139, USA
12. Neurogenomics, Translational Sciences, Neurology Business Group, Eisai Inc., Cambridge, MA 02140, USA

Best,
Dr. Himmelstein

<details>
<summary>Expand for code</summary>

```py
import requests

url = "https://github.com/greenelab/connectivity-search-manuscript/raw/aac01c50b685ab72b0b5a64355fe06381cefdf22/variables.json"
variables = requests.get(url).json( )

for author in variables["manubot"]["authors"]:
    print("{name} {numbers}".format(name=author["name"], numbers=",".join(map(str, author["affiliation_numbers"]))))

for affiliation in variables["manubot"]["affiliations"]:
    print(f"{affiliation['affiliation_number']}. {affiliation['affiliation']}")
```

</details>

## Reply on 2023-06-23

Dear Daniel,

Thanks again for your mail.

As per below mail, we have incorporated the below corrections into the mentioned article.

Please check and do let us know if any further assistance is required from our end.

Warm Regards,
Navneet Kumar
Technical Support | PXE

[`giad047-fixed-affiliations.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/11848610/giad047-fixed-affiliations.pdf)

**Comment by dhimmel** [comment]
# Equations

It looks like some equations failed to export to the DOCX and are therefore also omitted from the proof. We will need to go through every equation and check that it's present and correct.

So far I see 3 equations that did not convert. These all used align (which I think is from amsmath):

https://github.com/greenelab/connectivity-search-manuscript/blob/46e165b38bf3bf03e17dbdcaa19eae7c396bc284/content/05.main-text.md#L496-L501

In the PXE5 editor there where empty parenthesis next to the formulas when I entered the TeX math with `\begin{align}`. These went away when I switched to `\begin{align*}`, which disable per-line equation numbering.

Updated source in 7b4b9f1d5d363ffb56a8b1d8ed59f8e955de67ea

**Comment by dhimmel** [comment]
# Figures

Figures look pretty low resolution and like they were converted from PNG to JPG for the PDF embedding.

EPS files submitted for vector images in https://github.com/greenelab/connectivity-search-manuscript/issues/53.

The remaining raster images (Figure 1, 2, 7) need to be higher resolution. Text in Figure 2 is unreadable. On 2023-06-30, I emailed figures added in 564ed8d55da51dac396faeaf327443c541fb8cac

> I have verified that all figures with an EPS source now look good. The vector figures are 1, 4, 5, 6.
> 
> Figures 2, 3, and 7 have a raster source (no vector source is possible for these figures). I noticed the images are of low resolution and the text in the images is difficult to read. Therefore I've attached a zip file with higher resolution versions of these figures. Each figure is provided in PNG and JPG format. Does your system support PNG images (without converting them to JPG)? For Figures 2 and 3, the PNGs are both better quality and smaller file sizes.
> 
> Can you please use these higher resolution images in the attachment for the article, preferably the PNGs for Figures 2 and 3 (and optionally 7) if possible?

## Reply

Dear Dr. Himmelstein, Good Day!

As per our technical team figure 2,3,7 are raster images, although they are of good quality, they tend to downgrade in quality when PDF is generated. No further improvement is possible from graphics end. 

Please find the attached pdf.

Please check and let us know if there is any concern in this regard.

Regards,
Manish Chauhan
Technical Support | PXE


## Reply

Thanks Manish for your help. In the attached manuscript, can you confirm that you replaced the raster images with those from the earlier attachment?

I am concerned that the figures are illegible in the PDF, especially Figure 2D. Do the figures used for the web article also get downsized?

It would be a shame to publish an illegible image. To do so would reflect negatively on our research team, the journal Gigascience, Oxford University Press, and Aptara Inc. So please connect me directly with someone who can help us address this issue. Certainly a solution is possible and identifying the solution here will help countless other articles that encounter this problem.

Sincerely,
Dr. Himmelstein 


## Reply

Dear Dr. Himmelstein,

Thanks for your patience and cooperation with us.

We are checking the reported issue with our technical team and  informed you soon.

Regards,
Sunil Singh
Technical Support | PXE

***

Dear Dr. Himmelstein,

We have now reprocessed and updated figures 2,3,7 in best possible quality.

If you still have any concern regarding quality of images in this article then please provide high resolution figures of these images in EPS format.

Regards,
Sweta Sinha
Technical Support | PXE

[`2023-07-04_giad047.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/11951279/2023-07-04_giad047.pdf)

@dhimmel's note: small text is still unreadable in Figure 3D:

> ![image](https://github.com/greenelab/connectivity-search-manuscript/assets/1117703/f3ba7656-96c7-4349-98c2-557647042653)

**Comment by dhimmel** [comment]
# Title

The copyeditor changed the title to "Hetnet connectivity search provides rapid insights into how **2** biomedical entities are related". It looks like their stylistic preference is always use digits and not spell out numbers. I think this looks odd. We have 3 options:

1. 👍🏻 Accept the change, make sure they apply it everywhere (it is totally possible the copyeditor changes of the document do not copy over to the system metadata.
2. 👎🏻  Resist the change, ask to keep as **two**
3. 😆  Remove the number so title becomes "rapid insights into how biomedical entities are related"

You can vote on your preferred solution using an emoji reaction matching the ones in the list above.

**Comment by bdsullivan** [comment]
ranked voting: 😆 then 👎

**Comment by cgreene** [comment]
😆

**Comment by zietzm** [comment]
😆

**Comment by mnagleeisai** [comment]
😆

**Comment by dongbohu** [comment]
😆

**Comment by danich1** [comment]
😆

**Comment by dhimmel** [comment]
# Internal Section References

Are missing. Need to see if any Gigascience articles have internal references.

https://doi.org/10.1093/gigascience/giad043 does not link "see Methods" or "see Samples with Population Stratification section".

**Comment by dhimmel** [comment]
# Submitted

I just submitted the proof revisions. Here's the PDF proof: [`2023-07-08_giad047.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/11990693/2023-07-08_giad047.pdf) and the tracked changes from our proof review: [`2023-07-08_giad047-proof-changes.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/11990692/2023-07-08_giad047-proof-changes.pdf).

**Comment by dhimmel** [comment]
# Proof v2

Just received this email:

> Dear author,
> 
> We have implemented all the corrections in your paper attached please find the corrected PDF for your review.
> 
> Thanks & Regards,
> Sunita
> GIGSCI

Attachment: [`2023-07-20_giad047.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/12108299/2023-07-20_giad047.pdf)

I'll look over the proof now and leave any notes below or in an annotated PDF:

- All references now have URLs and the DOI resolver URL is used when there is a DOI. This is good. However, two non-DOI reference URLs have hyperlink targets that are different from the URL text. For example, reference 10 shows the URL `http://jmlr.org/papers/v22/20-825.html`, but then the link target is:

    ```
    http:\begingroup \count@ "002F\relax \relax \uccode `~\count@ \uppercase {\gdef {\relax \protect $\relax \sim $}}\endgroup \setbox \thr@@ \hbox {}\dimen \z@ \wd \thr@@ \begingroup \count@ "002F\relax \relax \uccode `~\count@ \uppercase {\gdef {\relax \protect $\relax \sim $}}\endgroup \setbox \thr@@ \hbox {}\dimen \z@ \wd \thr@@ jmlr.org\begingroup \count@ "002F\relax \relax \uccode `~\count@ \uppercase {\gdef {\relax \protect $\relax \sim $}}\endgroup \setbox \thr@@ \hbox {}\dimen \z@ \wd \thr@@ papers\begingroup \count@ "002F\relax \relax \uccode `~\count@ \uppercase {\gdef {\relax \protect $\relax \sim $}}\endgroup \setbox \thr@@ \hbox {}\dimen \z@ \wd \thr@@ v22\begingroup \count@ "002F\relax \relax \uccode `~\count@ \uppercase {\gdef {\relax \protect $\relax \sim $}}\endgroup \setbox \thr@@ \hbox {}\dimen \z@ \wd \thr@@ 20-825.html
    ```

Note that we can no longer access the PXE5 interface with the article with a diff from when we last reviewed the proof. I do see however that the manuscript was last modified by Rabindra Kumar Singh on 19-07-2023 08:05:03 PM.

## @dhimmel Response

Thank you Sunita! Glad to see that all the references now have URLs and the figures use vector sources (as per our previous correspondence).

I've noticed some additional issues, which I've noted using PDF annotations. You should see 7 annotation notes in the attached document [`2023-07-20_giad047-annotated.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/12111869/2023-07-20_giad047-annotated.pdf). Most should be quick to fix.

Let us know if you have any questions about these requests.

Best,
Daniel

Noting here that most of these issues existed with the original proof, I just had missed them since I was looking largely at the web interface rather than the PDF.

## Sunita response

On PDF page 13, two comments are still not clear. Could you please explain what is to be done.

## @dhimmel response

There are 3 comments on page 13. Please specify which comments are not clear and what aspect of the comments you are having difficulty understanding.

The first comment on page 13 is about an extra space. The third comment is about a missing space. The second comment is about additional text being hyperlinked beyond the blue text. This might be an issue with the typesetting software so could require a technical specialist. If this issue cannot be resolved in the PDF but the hyperlinks in the HTML version are properly scoped, then it is probably okay to publish. But in any case this is a bug or error that should be investigated.

## Sunita response

I have checked both the links are correct, pleases let me know, if still there is any issue. 

Attachment [`2023-07-23_giad047.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/12145790/2023-07-23_giad047.pdf)

## @dhimmel response

I have confirmed that most fixes from the PDF annotations have been performed.

Figure 4 has now moved locations, such that the Figures are ordered like 1, 4, 2, 3. Could you please restore the position of Figure 4 such that it appears in the Methods section of the manuscript? If the position of the figure is determined automatically based on mentions and you cannot override it, then a possible solution would be to update the first mention of the figure at  "to their degree (Fig. 4).", such that it does not actually link "4" to the figure. If there is no other solution, you can remove "(Fig. 4)" from that sentence entirely.

> I have checked both the links are correct

The issue affecting the bulleted list is not about the links resolving to the incorrect URLs. The issue is about the amount of text that becomes hyperlinked. For example, in the text "Registered at biotools:hetmatpy and [RRID:SCR_023409](https://scicrunch.org/resolver/RRID:SCR_023409)", the hyperlink should only apply to RRID:SCR_023409. However, if you click on "Registered" in the PDF, it also opens the destination URL. Is this possible to fix?

## Sunita Response

Please find the attached updated PDF. [`2023-07-26_giad047.pdf`](https://github.com/greenelab/connectivity-search-manuscript/files/12175490/2023-07-26_giad047.pdf)

1. We have corrected the figure numbering as 1, 2, 3 and 4 and removed text as "(Fig. 4)" from the sentence. Please check and confirm the correctness for the same.
2. As point number 2, we checked the link and it’s working fine and there is no link with text "Registered". Please check and confirm the correctness for the same.

## @dhimmel response

Hi Sunita,

1. Figures 1, 2, 3, and 4 now appear in order so that is good.
2. If you click on "Registered", it will bring you to the link (at least in my PDF viewer). But it might be difficult to diagnose the cause of this. Let's not worry about it anymore, since it seems unlikely to be fixable.

Let's proceed with publication!

Best,
Daniel

## Sunita response 2023-07-26

Thank you for your approval.

We will now process this ahead for publication.

**Comment by dhimmel** [comment]
Article is now published at <https://doi.org/10.1093/gigascience/giad047>, updated the manuscript with a link to GigaScience in https://github.com/greenelab/connectivity-search-manuscript/commit/54317f330b3f7139d0d7f03d4b1187d01017e9d0. Congrats team!

The figures in the HTML have problems: low resolution and mutated colors, created a dedicated issue at https://github.com/greenelab/connectivity-search-manuscript/issues/56.

**Comment by bdsullivan** [comment]
Hurrah - thanks for sticking with this all the way through. This is one of the worst copy-editing processes I've ever seen.

Blair

**Comment by cgreene** [comment]
OMG the figures in the online version... what... in... the... world!
